## Develop data management class

In [14]:
from importlib import reload
import data_management as dm
reload(dm)

<module 'data_management' from '/nfs/farm/g/glast/u/burnett/analysis/agn_timing/code/data_management.py'>

In [15]:
class Setup():
    def __init__(self, l=0,b=0, verbose=2):
        self.l,self.b,self.verbose=(l,b,verbose)

data = dm.Data(Setup(), mjd_range=(55e3, 56e3))

Found 127 monthly photon data files, with 4.6 GB total
Selected years [1 4], months [ 9 42]
Loading data from 33 months .................................
Selected 912785 photons within 5 deg of  (0.00,0.00)
	Date range: 2009-05-03 00:40     - 2012-02-01 11:19
	MJD:        54954.0              - 55958.5             


In [121]:
data.ft2_files

['/nfs/farm/g/glast/g/catalog/P8_P305/ft2_2009.fits',
 '/nfs/farm/g/glast/g/catalog/P8_P305/ft2_2010.fits',
 '/nfs/farm/g/glast/g/catalog/P8_P305/ft2_2011.fits']

In [78]:
            tlim =Time(mjd_range, format='mjd').datetime
            ylim,mlim = np.array([t.year for t in tlim])-2008, np.array([t.month for t in tlim])-1
            year_limits = np.min(0, np.max(ylim, len(files)))
            month_limits = np.min(0, np.max(ylim*12+mlim-8,len(ft2_files)))
            print(year_limits, month_limits)

NameError: name 'files' is not defined

In [87]:
np.max(np.array([-1,2]),initial=0)

2

In [47]:
years = np.array([Time(datetime(2008+i, 1, 1 )).mjd for i in range(10)])

array([54466., 54832., 55197., 55562., 55927., 56293., 56658., 57023.,
       57388., 57754.])

In [104]:
mjd_limits = (55e3,56e3)
tlim =Time(mjd_limits, format='mjd').datetime
ylim,mlim = np.array([t.year for t in tlim])-2008, np.array([t.month for t in tlim])-1
print(ylim,mlim)
#yindex = ylim=2008; mindex = ylim[1]-ylim[0]
year_range = ylim.clip(0, None)
month_range = (ylim*12+mlim-8).clip(0,None)
print(f'Selected years {year_range}, months {month_range}')

[1 4] [5 2]
Selected years [1 4], months [ 9 42]


In [110]:
z = np.array([1,3])
np.arange(10)[slice(*z)]

array([1, 2])

In [46]:
datetime?

Init signature: datetime(self, /, *args, **kwargs)
Docstring:     
datetime(year, month, day[, hour[, minute[, second[, microsecond[,tzinfo]]]]])

The year, month and day arguments are required. tzinfo may be None, or an
instance of a tzinfo subclass. The remaining arguments may be ints.
File:           /nfs/farm/g/glast/u/burnett/anaconda3/lib/python3.7/datetime.py
Type:           type
Subclasses:     _Timestamp, _NaT


In [11]:
from datetime import datetime
y,m=2008,8
t = Time(datetime(y,m, 1, 0, 0, 0), scale='utc')
t.mjd

54679.0

In [19]:
def mjd_months(y, m1=1, m2=12):
    return [Time(datetime(2007+y, m, 1,0, 0)).mjd for m in np.arange(m1,m2+1)]

In [20]:
months(1, 8,12)+months(2009, 1,12)

[54679.0, 54710.0, 54740.0, 54771.0]

In [23]:
Time(datetime(2008, 8, 1,0, 0)).mjd

54679.0

In [24]:
np.atleast_1d?

Signature: np.atleast_1d(*arys)
Docstring:
Convert inputs to arrays with at least one dimension.

Scalar inputs are converted to 1-dimensional arrays, whilst
higher-dimensional inputs are preserved.

Parameters
----------
arys1, arys2, ... : array_like
    One or more input arrays.

Returns
-------
ret : ndarray
    An array, or list of arrays, each with ``a.ndim >= 1``.
    Copies are made only if necessary.

See Also
--------
atleast_2d, atleast_3d

Examples
--------
>>> np.atleast_1d(1.0)
array([1.])

>>> x = np.arange(9.0).reshape(3,3)
>>> np.atleast_1d(x)
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])
>>> np.atleast_1d(x) is x
True

>>> np.atleast_1d(1, [3, 4])
[array([1]), array([3, 4])]
File:      /nfs/farm/g/glast/u/burnett/anaconda3/lib/python3.7/site-packages/numpy/core/shape_base.py
Type:      function
